
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afthfaddlxvqdvrhnaiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmdGhmYWRkbHh2cWR2cmhuYWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjM4NzgsImV4cCI6MjA2MDEzOTg3OH0.ZqA-UnfaGDxFZnqxfYetutAO0cvZ84gnCsA0sHx8BRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
